### ISSUE TITLE
RS485 bus transceiver wiring

### ISSUE THREAD

**Issue by pengemetal** [cribskip/esp8266_spa#9]
I have this type of RS485 bus transceiver, could you help me about wiring? Thx
![IMG_20210205_132747](https://user-images.githubusercontent.com/56131015/107034225-b565f980-67b6-11eb-96ae-ef277b796368.jpg)

**Comment by EmmanuelLM** [comment]
Evening, I had a lot of trouble with this transceiver so ended up getting a ARCELI TTL To RS485 Adapter 485 Serial Port UART Level Converter Module 3.3V 5V, so I would recommend getting one of those.
The main differences are:
- it natively runs at 3.3v or 5V
- you don't have to mess about with pulling D1 to transmit data
- it has some flashing lights that shows data being received / sent [helpful for debugging connections]

**Comment by pengemetal** [comment]
Thx, I'll try to order this  transceiver!

**Comment by pengemetal** [comment]
Hi, All parts have arrived I would start to make the connection. One question: I haven't got molex cable or Y splitter, is it possible to cut the display cable and with some Wago make DIY y-splitter cable? How did you wire to the motherboard? Thx!

**Comment by EmmanuelLM** [comment]
I mean... everything is possible and what you suggest is (in essence) a Y-slitter.
I got a mini Molex cable and connected to the spare port.

One question for you (and whoever else is ready this) - would there be any interest in buying a made-up system? Thinking out loud, I am thinking the whole system + 3d printed case would probably come to ~50USD or so?

**Comment by EspenT** [comment]
Yes, for 50usd I would buy 😊 I´ve been following this thread forever and probably have everything I would need to make it, except time.

From: EmmanuelLM ***@***.***>
Date: Wednesday, 31 March 2021 at 22:18
To: cribskip/esp8266_spa ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [cribskip/esp8266_spa] RS485 bus transceiver wiring (#9)

I mean... everything is possible and what you suggest is (in essence) a Y-slitter.
I got a mini Molex cable and connected to the spare port.

One question for you (and whoever else is ready this) - would there be any interest in buying a made-up system? Thinking out loud, I am thinking the whole system + 3d printed case would probably come to ~50USD or so?

**Comment by pengemetal** [comment]
Thx for the quick answer! I think it is a fair price for it!

**Comment by EmmanuelLM** [comment]
Sounds like I need to have a look at getting the wifi hotspot working then!

**Comment by cribskip** [comment]
@EmmanuelLM please add a connector for J2 (IIRC) to control the heater. That way controlling the circulation is possible and other cool things.

Currently I use a relay but an transistor should suffice

**Comment by mopac** [comment]
I realise it is a little late for the original poster, but just for completeness, I show here my schematic and a few photos of how I used this RS485 board.
I use a D1mini power sheild to regulate the hot tub 12V supply down to 5V for the RS485 board and the D1 Mini Pro. (D1 Mini Pro has its own regulator from 5V down to 3.3V.
The RS485 board is 5V, while D1 mini Pro is 3.3V. All outputs from D1 Mini Pro work just fine with a direct connection. The RX input - RO output from the RS485 board is the only issue. The fix is a schottky diode in this signal line. Schottky diode because of the low forward voltage. I used a BAT43 diode.
Tx & Rx used for the RS485 board are also connected to the USB-UART converter on the D1 Mini Pro but there are 470 ohm series resistors so they can be overdriven.
I use GPIO13 & GPIO15 for enabling the Receiver and Transmitter respectively. This is because GPIO13 has a pull-up on the D1 mini and GPIO15 has a pull-down. So if software doesn't configure these GPIO, the RS485 board is disabled. The benefit is that Serial download still works.
The only annoying tweak is that R3 on the RS485 board needs to be removed. This is a pull-up resistor that conflicts with the pull-down resistor on the GPIO15 on D1 mini Pro.
The only changes in the code are to configure the two GPIO as outputs and set LOW in the 'Setup' function. And ensure both GPIO are set HIGH then LOW in the 'rs485_send' function
![Hot_Tub_v1](https://user-images.githubusercontent.com/5881829/124570891-2fbaa880-de3f-11eb-8891-effaf2c6c95f.png)
![20210705_103116](https://user-images.githubusercontent.com/5881829/124570918-36492000-de3f-11eb-9791-4df75db44d0e.jpg)
![20210705_103248](https://user-images.githubusercontent.com/5881829/124570949-3c3f0100-de3f-11eb-8e25-50ecf9af1dc6.jpg)
![20210705_103320](https://user-images.githubusercontent.com/5881829/124570962-419c4b80-de3f-11eb-93a7-f9ddb3f1cdf2.jpg)
![20210705_103351](https://user-images.githubusercontent.com/5881829/124570973-45c86900-de3f-11eb-91c5-55ec27e348a9.jpg)
![20210705_103057](https://user-images.githubusercontent.com/5881829/124571534-c7b89200-de3f-11eb-8de1-933566ebaf64.jpg)
![20210705_103213](https://user-images.githubusercontent.com/5881829/124572740-ca67b700-de40-11eb-91a8-9dc86e2764a3.jpg)
